### PR TITLE
Update slack notifications channel

### PR DESCRIPTION
**Pull request by Marcin-Radecki**

### CODE REVIEW

**Review by youPickItUp — APPROVED** [review]
I think some polkadot mechanism has triggered on new year and it wants all headers updated... Not sure if it's only for their files or all files, but perhaps it would be simplest to roll with it? :sweat_smile: 

We can also try to find where it's coming from - I think @jalooc has some experience with that

**Comment by jalooc** [comment]
[We discussed this a longer while ago](https://cardinalcryptography.slack.com/archives/C05D7GGU3N0/p1687423011584569) and the resolution was to remove the eslint rule. I think we should just do it now. Any objections?

**Comment by youPickItUp** [comment]
> [We discussed this a longer while ago](https://cardinalcryptography.slack.com/archives/C05D7GGU3N0/p1687423011584569) and the resolution was to remove the eslint rule. I think we should just do it now. Any objections?

I don't mind, but don't we want to update the files created by polkadot? I'm not sure what sense does changing the copyright year **every year** make, but there's gotta be something to it if so many people do that... right? :sweat_smile: 

image
image

**Comment by jalooc** [comment]
Oh yeah, we can do that too.

**Comment by Marcin-Radecki** [comment]
Let me try to fix in the upstream PR which I plan to do right now. This PR contains only slack channel update so I'll merge it now.

**Pull request merged**
